### ISSUE TITLE
Any drawback implement this feature using GLSurfaceView?

### ISSUE THREAD

**Issue by b95505017** [fbsamples/360-video-player-for-android#5]
As title.

**Comment by 03lafaye** [comment]
In Nougat+, no since the SurfaceView will be synchronised with the View layout system. But in older versions you'll want TextureView if you don't plan to use a full screen view and will be showing the video in a non-static view that's part of a scrollable list or can be animated. SurfaceView, prior to Nougat, would draw it's surface behind the app surface and cut a hole through the app window to show its content, as such it didn't operate like a normal view that could be animated correctly.

**Comment by b95505017** [comment]
But if we want to play a protected (DRM) video, it looks like we could only use SurfaceView.
